Add browser_launch_timeout configuration option and improve launch timeout error message (#21)
closes #20

* Set a generous minimum GenServer timeout

Since the 0.5.0 release, we've seen in an issue in CI where our tests become unreliable due to GenServer timeouts.

For instance, if I do:

```elixir
refute_has(session, "div", text: "Should not exist", timeout: 100)
```

...it will often fail in our GitHub Actions CI, I assume because the CI machine is so dog slow that it can't shuttle a message between Playwright and PhoenixTest.Playwright within 150 milliseconds. Here's what the stacktrace looks like:

```
     ** (exit) exited in: GenServer.call(PhoenixTest.Playwright.Connection, {:post, %{metadata: %{}, params: %{timeout: 100, selector: "css=div >> visible=true >> internal:text=\"Should not exist\"i"}, method: :wait_for_selector, guid: "frame@55ce48fd95bf3348e115d23465662fcc"}}, 150)
         ** (EXIT) time out
     code: |> refute_has("div", text: "Should not exist", timeout: 100)
     stacktrace:
       (elixir 1.18.2) lib/gen_server.ex:1128: GenServer.call/3
       (phoenix_test_playwright 0.5.0) lib/phoenix_test/playwright/frame.ex:78: PhoenixTest.Playwright.Frame.wait_for_selector/2
       (phoenix_test_playwright 0.5.0) lib/phoenix_test/playwright.ex:551: PhoenixTest.Playwright.found?/3
       (phoenix_test_playwright 0.5.0) lib/phoenix_test/playwright.ex:515: PhoenixTest.Playwright.refute_has/3
       lib/jump_web/live/meeting_live_browser_test.exs:71: (test)
```

You can see there that the `GenServer.call/3` timeout was 150 (i.e., 1.5 times the 100 ms I specified I'd be willing to wait to confirm the text wasn't on the page).

My proposed fix is to set a minimum GenServer timeout of a second. That will ensure that you can specify a low timeout for refutations without risking a GenServer crash.

* Run Styler

* Add browser_launch_timeout configuration option and improve launch timeout error message

This improves the debuggability of the browser launch timing out, an issue we've seen quite a bit in CI at Jump.

I've also added an explicit option for controlling the timeout on the launch of the browser. Using the global `:timeout` option for the browser launch is painful because the browser launch is generally the slowest part of our test suite, and we'd like tighter default timeouts for things like refuting the existence of an element.

Note that the test here depends on changes from #19, which impacts the minimum GenServer timeout on these calls.

## Error message before

```
1) test launch_browser produces a reasonable error on timeout (PhoenixTest.Playwright.ConnectionTest)
test/phoenix_test/playwright/connection_test.exs:10
** (KeyError) key :result not found in: %{
error: %{
error: %{
message: "Timeout 1ms exceeded.",
name: "TimeoutError",
stack: "TimeoutError: Timeout 1ms exceeded.\n at ProgressController.run (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/progress.js:75:26)\n at Chromium.launch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/browserType.js:79:38)\n at BrowserTypeDispatcher.launch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/browserTypeDispatcher.js:35:40)\n at BrowserTypeDispatcher._handleCommand (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:94:40)\n at DispatcherConnection.dispatch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:361:39)"
}
},
id: 1,
log: [],
method: nil
}
code: Connection.launch_browser(:chromium, timeout: 1)
stacktrace:
(phoenix_test_playwright 0.5.0) lib/phoenix_test/playwright/connection.ex:62: PhoenixTest.Playwright.Connection.launch_browser/2
test/phoenix_test/playwright/connection_test.exs:11: (test)
```

## Error message after

```
1) test launch_browser produces a reasonable error on timeout (PhoenixTest.Playwright.ConnectionTest)
test/phoenix_test/playwright/connection_test.exs:10
** (RuntimeError) Timed out while launching the Playwright browser, Chromium. Timeout 1ms exceeded.

You may need to increase the :browser_launch_timeout option in config/test.exs:

config :phoenix_test,
playwright: [
browser_launch_timeout: 10_000,
# other Playwright options...
],
# other phoenix_test options...

Playwright backtrace:

TimeoutError: Timeout 1ms exceeded.
at ProgressController.run (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/progress.js:75:26)
at Chromium.launch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/browserType.js:79:38)
at BrowserTypeDispatcher.launch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/browserTypeDispatcher.js:35:40)
at BrowserTypeDispatcher._handleCommand (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:94:40)
at DispatcherConnection.dispatch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:361:39)

code: Connection.launch_browser(:chromium, browser_launch_timeout: 1)
stacktrace:
(phoenix_test_playwright 0.5.0) lib/phoenix_test/playwright/connection.ex:73: PhoenixTest.Playwright.Connection.launch_browser/2
test/phoenix_test/playwright/connection_test.exs:11: (test)
```

Resolves #20