Add browser_launch_timeout configuration option and improve launch timeout error message
This improves the debuggability of the browser launch timing out, an issue we've seen quite a bit in CI at Jump.

I've also added an explicit option for controlling the timeout on the launch of the browser. Using the global `:timeout` option for the browser launch is painful because the browser launch is generally the slowest part of our test suite, and we'd like tighter default timeouts for things like refuting the existence of an element.

Note that the test here depends on changes from #19, which impacts the minimum GenServer timeout on these calls.

## Error message before

```
1) test launch_browser produces a reasonable error on timeout (PhoenixTest.Playwright.ConnectionTest)
test/phoenix_test/playwright/connection_test.exs:10
** (KeyError) key :result not found in: %{
error: %{
error: %{
message: "Timeout 1ms exceeded.",
name: "TimeoutError",
stack: "TimeoutError: Timeout 1ms exceeded.\n at ProgressController.run (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/progress.js:75:26)\n at Chromium.launch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/browserType.js:79:38)\n at BrowserTypeDispatcher.launch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/browserTypeDispatcher.js:35:40)\n at BrowserTypeDispatcher._handleCommand (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:94:40)\n at DispatcherConnection.dispatch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:361:39)"
}
},
id: 1,
log: [],
method: nil
}
code: Connection.launch_browser(:chromium, timeout: 1)
stacktrace:
(phoenix_test_playwright 0.5.0) lib/phoenix_test/playwright/connection.ex:62: PhoenixTest.Playwright.Connection.launch_browser/2
test/phoenix_test/playwright/connection_test.exs:11: (test)
```

## Error message after

```
1) test launch_browser produces a reasonable error on timeout (PhoenixTest.Playwright.ConnectionTest)
test/phoenix_test/playwright/connection_test.exs:10
** (RuntimeError) Timed out while launching the Playwright browser, Chromium. Timeout 1ms exceeded.

You may need to increase the :browser_launch_timeout option in config/test.exs:

config :phoenix_test,
playwright: [
browser_launch_timeout: 10_000,
# other Playwright options...
],
# other phoenix_test options...

Playwright backtrace:

TimeoutError: Timeout 1ms exceeded.
at ProgressController.run (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/progress.js:75:26)
at Chromium.launch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/browserType.js:79:38)
at BrowserTypeDispatcher.launch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/browserTypeDispatcher.js:35:40)
at BrowserTypeDispatcher._handleCommand (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:94:40)
at DispatcherConnection.dispatch (/Users/tyler/Documents/repos/phoenix_test_playwright/priv/static/assets/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:361:39)

code: Connection.launch_browser(:chromium, browser_launch_timeout: 1)
stacktrace:
(phoenix_test_playwright 0.5.0) lib/phoenix_test/playwright/connection.ex:73: PhoenixTest.Playwright.Connection.launch_browser/2
test/phoenix_test/playwright/connection_test.exs:11: (test)
```

Resolves #20