Fix failure to open trace when :trace_dir is an absolute path
This fixes an issue we ran into at work. We had set our `:trace_dir` configuration to `"/tmp/traces"`, and when we tried to run with `trace: :open`, we would get an error like the following printed to the console:

> Error: Trace file /Users/tyler/jump/api/tmp/traces/JumpWeb.Components.Core.PickerBrowserTest.test_can_search_within_a_picker_1769012948_9.zip does not exist!

This makes it so that both relative and absolute trace paths are supported.